### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by japkozet** [skandasoft/pp#12]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [pp](https://github.com/skandasoft/pp) package 0.0.1

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At /Users/japkozet/.atom/packages/pp/lib/pp-status-view.coffee:57

TypeError: Cannot read property 'id' of undefined
    at PPStatusView.toggleLive (/packages/pp/lib/pp-status-view.coffee:57:38)
    at /packages/pp/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLSpanElement.dispatch (/packages/pp/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLSpanElement.elemData.handle (/packages/pp/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
```

### Non-Core Packages

```
api-docs 0.0.6 
atom-beautify 0.29.23 
atom-css-comb 3.1.0 
atom-html-preview 0.1.22 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.10 
atom-webbrowser 2.1.4 
autoclose-html 0.23.0 
autocomplete-html-entities 0.1.0 
autocomplete-java 1.2.5 
autocomplete-paths 1.0.5 
browser-plus 0.0.87 
busy-signal 1.4.1 
color-picker 2.2.5 
colornamer 0.3.1 
css-color-name 0.4.0 
css-grid-snippets 1.0.9 
css-snippets 1.1.0 
csslint 1.1.5 
dracula-theme 2.0.3 
emmet 2.4.3 
git-plus 7.7.0 
git-projects 1.17.0 
intentions 1.1.2 
javascript-snippets 1.2.1 
language-javascript-better 1.7.1 
language-javascript-semantic 0.2.1 
linter 2.1.4 
linter-csslint 1.3.4 
linter-eslint 8.1.7 
linter-htmlhint 1.3.3 
linter-jshint 3.0.3 
linter-sass-lint 1.7.4 
linter-scss-lint 3.1.0 
linter-spell-javascript 0.7.2 
linter-ui-default 1.2.3 
open-in-browser 0.5.0 
pigments 0.39.1 
pp 0.0.1 
preview 0.17.0 
project-manager 3.3.4 
redux-devtools 0.5.1 
Remote-FTP 0.10.7 
sass-autocompile 0.13.3 
sass-compiler 0.4.0 
webbox-color 0.5.9 
```

**Comment by DeltaSigma130** [comment]
I am receiving the same error.

[Enter steps to reproduce:]

1. Simply turning on Markdown Preview Plus opens the preview tab, but the error is immediate.

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [pp](https://github.com/skandasoft/pp) package 0.0.1


### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At C:\Users\<USER>\.atom\packages\pp\lib\pp-status-view.coffee:57

TypeError: Cannot read property 'id' of undefined
    at PPStatusView.toggleLive (/packages/pp/lib/pp-status-view.coffee:57:39)
    at /packages/symbols-tree-view/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLSpanElement.dispatch (/packages/symbols-tree-view/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLSpanElement.elemData.handle (/packages/symbols-tree-view/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -6:36.5.0 editor:newline (input.hidden-input)
  4x -6:30.6.0 core:backspace (input.hidden-input)
     -5:55.2.0 editor:newline (input.hidden-input)
     -5:30.6.0 core:backspace (input.hidden-input)
  2x -5:11.6.0 editor:newline (input.hidden-input)
     -5:06.4.0 core:save (input.hidden-input)
     -5:04.1.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -5:02.6.0 pane:show-next-recently-used-item (input.hidden-input)
     -5:01.9.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
     -4:59.8.0 core:save (input.hidden-input)
     -4:46.7.0 markdown-preview-plus:toggle (input.hidden-input)
     -4:39 markdown-preview-plus:select-syntax-theme (atom-pane.pane.active)
     -4:28.8.0 markdown-preview-plus:toggle-render-latex (atom-pane.pane.active)
  2x -4:17.4.0 key-binding-resolver:toggle (atom-pane.pane.active)
     -2:20 settings-view:open (input.hidden-input)
     -1:29.7.0 markdown-preview-plus:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-diary 1.2.1 
atom-ide-ui 0.13.0 
file-types 1.0.1 
Hydrogen 2.13.1 
ide-yaml 0.6.0 
markdown-preview-plus 3.11.5 
pp 0.0.1 
pp-markdown 0.0.2 
symbols-tree-view 0.14.0 
vim-mode-plus 1.36.4 
vim-mode-plus-keymaps-for-surround 0.2.1 
vim-mode-plus-move-to-symbols 0.5.0 
```
