### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by skull-squadron** [skandasoft/pp#4]
- Atom Beta 1.12.0-beta3
- pp@0.0.1
- pp-markdown@0.0.2

```
Uncaught TypeError: Cannot read property 'getPath' of undefined
at {{redacted}}/.atom/packages/pp/lib/pp.coffee:140

TypeError: Cannot read property 'getPath' of undefined
    at Object.getExt ({{redacted}}/.atom/packages/pp/lib/pp.coffee:140:24)
    at Object.getPreviews ({{redacted}}/.atom/packages/pp/lib/pp.coffee:123:29)
    at PPStatusView.previewList ({{redacted}}/.atom/packages/pp/lib/pp-status-view.coffee:80:23)
    at HTMLSpanElement.<anonymous> ({{redacted}}/.atom/packages/pp/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLSpanElement.dispatch ({{redacted}}/.atom/packages/pp/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLSpanElement.elemData.handle ({{redacted}}/.atom/packages/pp/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4121:28)
The error was thrown from the pp package. You can help by creating an issue. Please explain what actions triggered this error.
Create issue on the pp package
```

**Comment by skull-squadron** [comment]
Looking a hemorrhaging-edge issue: happens when clicking on live when the focused window isn't an editor.

Might want to gray-out <kbd>Live🔻</kbd> when it's not possible?
